### PR TITLE
#162600674 sigin page

### PR DESCRIPTION
**Pull request by Wabuluka**
#### What does this PR do?
The sign in page 
#### Description of Task to be completed?
This PR contains the css and html for the signin page

### CODE REVIEW

**Comment by KapsonLabs** [comment]
PR seems clean. Git Workflow quite on point too. 
Ur **README** though is empty so the repo kind of has no description to keep visitors up to speed with what you are doing.

**Comment by Wabuluka** [comment]
thank you for this feedback. Let me update the read.md as soon as possible

**Comment by bekeplar** [comment]
Create more descriptive READ ME.md

**Comment by Wabuluka** [comment]
thank you very much for the feedback, let me work on it as soon as possible

**Pull request merged**
